from sqlalchemy import Column, Integer, String, Date, Boolean, DateTime, ForeignKey, UniqueConstraint
from sqlalchemy.sql import func
from sqlalchemy.orm import relationship
from app.db.session import Base


class FeeStructure(Base):
    """
    Fee structure per class and academic year
    """
    __tablename__ = "fee_structures"
    __table_args__ = (
        UniqueConstraint('class_id', 'academic_year_id', name='uq_class_academic_year'),
    )

    id = Column(Integer, primary_key=True, index=True)
    class_id = Column(Integer, ForeignKey("classes.id"), nullable=False)
    academic_year_id = Column(Integer, ForeignKey("academic_years.id"), nullable=False)

    # Fee components (stored as paise: 100 paise = 1 rupee)
    tuition_fee = Column(Integer, nullable=False)
    hostel_fee = Column(Integer, default=0)

    created_at = Column(DateTime, server_default=func.now())

    # Relationships
    class_ = relationship("Class", back_populates="fee_structures")
    academic_year = relationship("AcademicYear", back_populates="fee_structures")

    def __repr__(self):
        return f"<FeeStructure Class:{self.class_id} Year:{self.academic_year_id}>"


class MonthlyFee(Base):
    """
    Monthly fee record for each student
    Pre-generated by the system with SMS tracking
    """
    __tablename__ = "monthly_fees"
    __table_args__ = (
        UniqueConstraint('student_id', 'academic_year_id', 'month', 'year', name='uq_student_month_year'),
    )

    id = Column(Integer, primary_key=True, index=True)
    student_id = Column(Integer, ForeignKey("students.id"), nullable=False, index=True)
    academic_year_id = Column(Integer, ForeignKey("academic_years.id"), nullable=False)
    month = Column(Integer, nullable=False)  # 1-12
    year = Column(Integer, nullable=False)

    # Fee breakdown (stored as paise)
    tuition_fee = Column(Integer, nullable=False)
    hostel_fee = Column(Integer, default=0)
    transport_fee = Column(Integer, default=0)
    total_fee = Column(Integer, nullable=False)

    # Payment status
    amount_paid = Column(Integer, default=0)
    amount_pending = Column(Integer, nullable=False)
    status = Column(String(20), default="pending", index=True)  # pending, paid, partial

    # Dates
    due_date = Column(Date, nullable=False, index=True)
    generated_at = Column(DateTime, server_default=func.now())

    # SMS tracking
    sms_sent = Column(Boolean, default=False)
    sms_sent_at = Column(DateTime, nullable=True)
    reminder_sent = Column(Boolean, default=False)
    reminder_sent_at = Column(DateTime, nullable=True)

    # Relationships
    student = relationship("Student", back_populates="monthly_fees")
    academic_year = relationship("AcademicYear", back_populates="monthly_fees")
    payments = relationship("Payment", back_populates="monthly_fee")

    def __repr__(self):
        return f"<MonthlyFee Student:{self.student_id} {self.month}/{self.year} - ₹{self.total_fee/100:.2f}>"
